version: "3"

services:

  epayment-server:
    container_name: epayment-server
    image: "ramesesinc/enterprise-common-server:255.03.001"
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports: 
      - "8095:8070"
    volumes:
      - ../../_res/connections:/apps/enterprise/connections/ext
      - ../../_custom/datasources/epaymentds:/services/datasources/mainds

      - ./modules:/apps/enterprise/modules
